# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.k2triangleC <- function(d1, d2, d3) {
    .Call('_vegclust_k2triangle', PACKAGE = 'vegclust', d1, d2, d3)
}

.triangleinequalityC <- function(d1, d2, d3, tol = 0.0001) {
    .Call('_vegclust_triangleinequality', PACKAGE = 'vegclust', d1, d2, d3, tol)
}

.ismetricC <- function(dmat, tol = 0.0001) {
    .Call('_vegclust_ismetric', PACKAGE = 'vegclust', dmat, tol)
}

.projectionC <- function(dref, d1, d2, add = TRUE) {
    .Call('_vegclust_projection', PACKAGE = 'vegclust', dref, d1, d2, add)
}

.angleConsecutiveC <- function(d12, d23, d13, add = TRUE) {
    .Call('_vegclust_angularAttributeConsecutive', PACKAGE = 'vegclust', d12, d23, d13, add)
}

.distanceToSegmentC <- function(dref, d1, d2, add = TRUE) {
    .Call('_vegclust_distanceToSegment', PACKAGE = 'vegclust', dref, d1, d2, add)
}

.twoSegmentDistanceC <- function(dmat12, type = "directed-segment") {
    .Call('_vegclust_twoSegmentDistance', PACKAGE = 'vegclust', dmat12, type)
}

