# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.projectionC <- function(dref, d1, d2) {
    .Call('_vegclust_projection', PACKAGE = 'vegclust', dref, d1, d2)
}

.distanceToSegmentC <- function(dref, d1, d2) {
    .Call('_vegclust_distanceToSegment', PACKAGE = 'vegclust', dref, d1, d2)
}

.twoSegmentDistanceC <- function(dmat12, type = "directed-segment") {
    .Call('_vegclust_twoSegmentDistance', PACKAGE = 'vegclust', dmat12, type)
}

.triangleinequalityC <- function(d1, d2, d3, tol = 0.0001) {
    .Call('_vegclust_triangleinequality', PACKAGE = 'vegclust', d1, d2, d3, tol)
}

.ismetricC <- function(dmat, tol = 0.0001) {
    .Call('_vegclust_ismetric', PACKAGE = 'vegclust', dmat, tol)
}

