# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Functions for trajectory analysis
#' 
#' Besse, P., Guillouet, B., Loubes, J.-M. & François, R. (2016). Review and perspective for distance based trajectory clustering. IEEE Trans. Intell. Transp. Syst., 17, 3306–3317.
#'
#' De Caceres M, Coll L, Legendre P, Allen RB, Wiser SK, Fortin MJ, Condit R & Hubbell S. (in preparation). Trajectory analysis in community ecology.
#'
#' Projection of one point into a (directed) segment
#'
#' @param dref Distance between the two segment endpoints
#' @param d1 Distance from the target point to the initial segment endpoint
#' @param d2 Distance from the target point to the final segment endpoint
.projectionC <- function(dref, d1, d2) {
    .Call('_vegclust_projection', PACKAGE = 'vegclust', dref, d1, d2)
}

#'
#' Distance from one point to one segment
#'
.distanceToSegmentC <- function(dref, d1, d2) {
    .Call('_vegclust_distanceToSegment', PACKAGE = 'vegclust', dref, d1, d2)
}

#'
#' Distance between two segments
#'
.twoSegmentDistanceC <- function(dmat12, type = "directed-segment") {
    .Call('_vegclust_twoSegmentDistance', PACKAGE = 'vegclust', dmat12, type)
}

#'
#' Triangle inequality for one triplet
#'
.triangleinequalityC <- function(d1, d2, d3, tol = 0.0001) {
    .Call('_vegclust_triangleinequality', PACKAGE = 'vegclust', d1, d2, d3, tol)
}

#'
#' Determines if the matrix fulfills the triangle inequality
#'
.ismetricC <- function(dmat, tol = 0.0001) {
    .Call('_vegclust_ismetric', PACKAGE = 'vegclust', dmat, tol)
}

